### ISSUE TITLE
README example doesn't work

### ISSUE THREAD

**Issue by porjo** [domainr/whois#10]
Compiling the code from the README:
```Go
query := "domai.nr"
request, err := whois.NewRequest(query)
response, err := whois.DefaultClient.Fetch(request)
record, err := response.Parse()
```
Results in error:
`response.Parse undefined (type *whois.Response has no field or method Parse)`

**Comment by case** [comment]
@porjo apologies for this, parsing functionality hasn't been implemented yet. I just updated the code comments in the examples to note this.
