### ISSUE TITLE
[Consult] How to parse WHOIS records

### ISSUE THREAD

**Issue by serima** [domainr/whois#12]
I know that WHOIS records are in a very complex situation though I want to implement parser to this project.
Which do you think is better?
I hope that you make a decision about future direction to parse.

1. pattern matching
  * inspired by [another whois project](https://github.com/likexian/whois-parser-go)
2. some algorithms
  * I found some papers
    * http://ian.ucsd.edu/papers/imc15-whois.pdf
    * http://cs229.stanford.edu/proj2013/TanLiXing-ParsingDomainWhoIsInformationwithDifferentPatternsUsingOneGenericParser.pdf

Either way, we cannot fully parse them.

I think No.1 is better for the following reasons.

* easy to add/delete new rules
* you can catch the failing of parse because domainr is in production fortunately.

**Comment by case** [comment]
Apologies for the delay here, parsing isn't currently on our high-priority task list.

You might consider forking this repo and experimenting with these different approaches?

**Comment by serima** [comment]
Thank you for replying. I understand your situation well.
I've already forked this repo, will try various things with that.

Thanks!
