### ISSUE TITLE
Removing dependency on syscall

### ISSUE THREAD

**Issue by bramp** [domainr/whois#13]
I'm trying to use domainr/whois on AppEngine. Due to the way AppEngine works, it disallows certain packages, one of which is syscall.

It seems syscall is used here https://github.com/domainr/whois/blob/master/client.go#L140 only for printing out a error message. Would it be possible to just drop the use of that? The standard syscall.Errno.Error() function prints out a reasonable error, so no need to do something special.

Willing to make this change? Thanks

**Comment by ydnar** [comment]
@bramp thanks for the request. We’d welcome a PR!
