### ISSUE TITLE
Could you share binary code(s) please?

### ISSUE THREAD

**Issue by rdonmez** [domainr/whois#8]
I have been trying to install on windows system but it doesn't anything when i run "go install" command.

I m interesting domainr whois cleint binary codes for my project. no development. 

thanks.

**Comment by ydnar** [comment]
@rdonmez what are you trying to do, exactly?

This is a library meant for inclusion in another program, not a user-facing tool. I suppose in theory you could install the client (thus having a random binary on your system named “client”) with this command:

`go get github.com/domainr/whois/cmd/client`
