### ISSUE TITLE
Insufficient results for some queries

### ISSUE THREAD

**Issue by avishbran** [domainr/whois#9]
Looks like some results are truncated by the package:

When running a query on nba.com, for example, the result is:

```
Domain Name: NBA.COM
   Registrar: CSC CORPORATE DOMAINS, INC.
   Sponsoring Registrar IANA ID: 299
   Whois Server: whois.corporatedomains.com
   Referral URL: http://www.cscglobal.com/global/web/csc/digital-brand-services
   Name Server: NS40.NBA.COM
   Name Server: NS50.NBA.COM
   Name Server: NS60.NBA.COM
   Status: clientTransferProhibited https://www.icann.org/epp#clientTransferProhibited
   Updated Date: 23-nov-2014
   Creation Date: 28-nov-1994
   Expiration Date: 27-nov-2016
```

However, the EXPECTED result, as received by 'whois' terminal command, should be:

```
Domain Name: nba.com
Registry Domain ID: 966915_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.corporatedomains.com
Registrar URL: www.cscprotectsbrands.com
Updated Date: 2014-11-23T06:21:37Z
Creation Date: 1994-11-28T05:00:00Z
Registrar Registration Expiration Date: 2016-11-27T05:00:00Z
Registrar: CSC CORPORATE DOMAINS, INC.
Sponsoring Registrar IANA ID: 299
Registrar Abuse Contact Email: domainabuse@cscglobal.com
Registrar Abuse Contact Phone: +1.8887802723
Domain Status: clientTransferProhibited http://www.icann.org/epp#clientTransferProhibited
Registry Registrant ID:
Registrant Name: C/O Domain Administrator
Registrant Organization: NBA Media Ventures, LLC
Registrant Street: 645 Fifth Avenue
Registrant City: New York
Registrant State/Province: NY
Registrant Postal Code: 10022
Registrant Country: US
Registrant Phone: +001.201.8651506
Registrant Phone Ext:
Registrant Fax: +000.000.0000000
Registrant Fax Ext:
Registrant Email: internicadmin@nba.com
Registry Admin ID:
Admin Name: Information Technology
Admin Organization: NBA Basketball Association
Admin Street: 100 Plaza Drive 3rd Fl
Admin City: Secaucus
Admin State/Province: NJ
Admin Postal Code: 07094
Admin Country: US
Admin Phone: +001.201.9746996
Admin Phone Ext:
Admin Fax: +001.201.9746001
Admin Fax Ext:
Admin Email: internicadmin@nba.com
Registry Tech ID:
Tech Name: Information Technology
Tech Organization: NBA Basketball Association
Tech Street: 100 Plaza Drive 3rd Fl
Tech City: Secaucus
Tech State/Province: NJ
Tech Postal Code: 07094
Tech Country: US
Tech Phone: +001.201.9746996
Tech Phone Ext:
Tech Fax: +001.201.9746001
Tech Fax Ext:
Tech Email: internicadmin@nba.com
Name Server: ns60.nba.com
Name Server: ns40.nba.com
Name Server: ns50.nba.com
DNSSEC: unsigned
```

**Comment by cee-dub** [comment]
Perhaps the connection was reset. Are you able to reproduce this reliably? If so, please provide steps.

You may set the response read size limit via `DefaultReadLimit` Which is 1MB by default.

**Comment by avishbran** [comment]
This behavior is consistent. The expected output size is 6565 bytes long, so it does not look like a size limit issue.
I am running the following code:
```go
package main

import (
	"fmt"
	"github.com/domainr/whois"
)

func main() {
	
	query := "nba.com"
	request, err := whois.NewRequest(query)
	if err != nil {
		fmt.Println(err)
		return
	}
	response, err := whois.DefaultClient.Fetch(request)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(response.String())
}
```

**Comment by avishbran** [comment]
Looks like the terminal 'whois' command is making a follow-up request (on a 2nd whois server), according to wireshark capture

**Comment by cee-dub** [comment]
Thank you for the additional information.

As you may observe in this package's code, it creates a single connection, writes the query to that connection, and then reads the entire response. What is the character of the extra request that your CLI client is making?

**Comment by avishbran** [comment]
Ok, the first query for nba.com is answered with an identical information as this package:
```
Domain Name: NBA.COM
   Registrar: CSC CORPORATE DOMAINS, INC.
   Sponsoring Registrar IANA ID: 299
   Whois Server: whois.corporatedomains.com
   Referral URL: http://www.cscglobal.com/global/web/csc/digital-brand-services
   Name Server: NS40.NBA.COM
   Name Server: NS50.NBA.COM
   Name Server: NS60.NBA.COM
   Status: clientTransferProhibited https://www.icann.org/epp#clientTransferProhibited
   Updated Date: 23-nov-2014
   Creation Date: 28-nov-1994
   Expiration Date: 27-nov-2016
```

Note the following line in the response above: **Whois Server: whois.corporatedomains.com**
The CLI client is making a 2nd query for nba.com to **whois.corporatedomains.com**, which results in a more detailed information.

**Comment by cee-dub** [comment]
I see. So rather than reading an incomplete response, this package is returning the entire response. It does not, however, send follow-up requests to the host listed after `Whois Server:`. Doing so seems like the responsibility of code using this package, rather than the package itself.

**Comment by case** [comment]
Re-opening this issue, as we've looked into it for use on domainr.com and understand the problem a bit more now.

Here's a description of the needed functionality, for when we can make time to implement:

1. Parse the whois response for this pattern: `Whois Server: {hostname}`
2. Find the last instance of the pattern (e.g. there are several spammy entries in the initial `apple.com` whois response), which is the canonical whois server for the domain.
3. Make a followup whois request to the newly found canonical host.
4. Respond appropriately. e.g. the Unix whois client appears to return both the initial and followup responses.

**Comment by remiphilippe** [comment]
I have a fix here: https://github.com/remiphilippe/whois/blob/new-parser/client.go#L100 the idea is to use a regex to capture domain (query might be different, for example if you use domain apple.com) and whois, then if current whois is different from query whois and if it's not empty (.org for example) we recurse. I only keep the response from the authoritative whois.

Didn't submit a pull request for now, want to understand the performance toll of this (in the same branch I've implemented parsing, but again regexp).

**Comment by cee-dub** [comment]
To begin with, you'll get much better performance if you compile the regexps once, not each request.

**Comment by ydnar** [comment]
Closing this. Clients of this library can parse out delegated whois server from "thin" whois servers and retry the query.
